// Generated by scripts/witnessed_timeline.py from the externally
// witnessed record chain (records/witnessed-timeline.json).
// Custody-root rows only: the site's publication-proof chronology
// tier joins predictionRun.custodyRootSha256 against these entries.
// Regenerate, don't hand-edit.
import type { WitnessedCustodyRootMap } from "./witnessed-timeline";

export const WITNESSED_TIMELINE_SCHEMA_VERSION =
  "thesis_witnessed_timeline_v1";

export const WITNESSED_CUSTODY_ROOTS: WitnessedCustodyRootMap =
  {
    "095881744f2328133379c7d1f5258f790397d4552c4b58ee1df395d37efdab86": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": true,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    },
    "09f2231bf83639589988a2ad87f76d7c3a7bff001dc9fc477f78b7d66bbde857": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T15:29:57Z",
      "headlineEligible": false,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T15:29:57Z",
      "witnessDigest": "records/2026-07-10/digest-29103805372-1.json"
    },
    "0a22ac0d58522d3a6a2e93b2d6e1706f5faba6badad0404fa20f3b4f482a82c9": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T06:24:38Z",
      "headlineEligible": false,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T06:24:38Z",
      "witnessDigest": "records/2026-07-10/digest-29073710752-1.json"
    },
    "0a786aada6ecdad0d5847810fb3d342a89003301bb5ecba367e58fb693f4e565": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T15:29:57Z",
      "headlineEligible": false,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T15:29:57Z",
      "witnessDigest": "records/2026-07-10/digest-29103805372-1.json"
    },
    "0c1e5bc014c0489698f5d76e5a75d0ab6e39133ebdc05bdd0a7bc712325e50d7": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": true,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    },
    "0c24a381bd158698b4f320f0aae5a7fa24d0ab3c9b2f94364924093d044b921f": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T15:29:57Z",
      "headlineEligible": false,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T15:29:57Z",
      "witnessDigest": "records/2026-07-10/digest-29103805372-1.json"
    },
    "0d433266c6a88142a4e4ebcaca3418aaf891ea9dcf33628ff37e5ace988d92b4": {
      "coverage": "direct",
      "custodyInventoryVersion": 1,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": false,
      "inventoryStatus": "legacy-incomplete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    },
    "0d5b44d3ebf8c5a68c4364fe4465ca4ade717b770eeaab7e4a9f738e9a02d9a1": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": true,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    },
    "0ecad61ea5dea5c2361aa29d5230f1d00dfc85e2afe42d30f466b8fbb20bb9ac": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T14:05:53Z",
      "headlineEligible": false,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T14:05:53Z",
      "witnessDigest": "records/2026-07-10/digest-29098454379-1.json"
    },
    "13245621651243a9836bed2d20c74f049134a71b584cb091c453466309012db9": {
      "coverage": "direct",
      "custodyInventoryVersion": 1,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": false,
      "inventoryStatus": "legacy-incomplete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    },
    "18441b057a2854a335f46cec869a2cc1a0b7397421c3b86a7e216a38647f162a": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T06:24:38Z",
      "headlineEligible": true,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T06:24:38Z",
      "witnessDigest": "records/2026-07-10/digest-29073710752-1.json"
    },
    "19b27591e92f6e780794d8afe64451398340ab7d01695c242dbdda57c2253c31": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": true,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    },
    "1ce5693e77d40688c5c1a0adba248d49fbda6fb4f184bc6e872ab037c6237b2e": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": true,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    },
    "1d3816a3c1f762f3851af9350f4435a62bdb0b04cb3a92347342d392278a7caa": {
      "coverage": "direct",
      "custodyInventoryVersion": 1,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": false,
      "inventoryStatus": "legacy-incomplete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    },
    "1e44739ce433e986b658e26a7168c214f2fb07c6408418f42aa73dfe3f322807": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T14:05:53Z",
      "headlineEligible": true,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T14:05:53Z",
      "witnessDigest": "records/2026-07-10/digest-29098454379-1.json"
    },
    "205ac1608d4c0c7ddee65ea1e0a73b9750cf414341e32ebf9d52359c785bf09f": {
      "coverage": "direct",
      "custodyInventoryVersion": 1,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": false,
      "inventoryStatus": "legacy-incomplete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    },
    "20ec109d800ac35671cec8df978f123ba797e8b25b0fc911fad92051bfb2d84a": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T15:29:57Z",
      "headlineEligible": true,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T15:29:57Z",
      "witnessDigest": "records/2026-07-10/digest-29103805372-1.json"
    },
    "2172d7b1cdd5300fc781f311659451fa3cf659aa805fd9fc2052836391478f8f": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T15:29:57Z",
      "headlineEligible": false,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T15:29:57Z",
      "witnessDigest": "records/2026-07-10/digest-29103805372-1.json"
    },
    "2331ef202b9ad4ac1e7fa5b1f515410f5758732784af9fe96a2db0977ed6ac1a": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T15:29:57Z",
      "headlineEligible": false,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T15:29:57Z",
      "witnessDigest": "records/2026-07-10/digest-29103805372-1.json"
    },
    "24342cea1c4cf143152f6ce15da414008555981e41d68dd53fd21cbd49de5b7f": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T15:29:57Z",
      "headlineEligible": true,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T15:29:57Z",
      "witnessDigest": "records/2026-07-10/digest-29103805372-1.json"
    },
    "24a416210ee19273e17b84defa62c2fe41541122ef4b0ee8ad17be722d3fbda7": {
      "coverage": "direct",
      "custodyInventoryVersion": 1,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": false,
      "inventoryStatus": "legacy-incomplete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    },
    "2546ecd932992953da63bffa8e25db6c1e65c3d139c35e95498d544f7e0aa2fc": {
      "coverage": "direct",
      "custodyInventoryVersion": 1,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": false,
      "inventoryStatus": "legacy-incomplete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    },
    "25809aec33511ad7dccadc82445a7172823806f7f2ce39a80a8a0a9033882990": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T15:29:57Z",
      "headlineEligible": false,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T15:29:57Z",
      "witnessDigest": "records/2026-07-10/digest-29103805372-1.json"
    },
    "295cdaa1199621fd5c291b5f3509bc01bf784598f465aa299590926df3a68f59": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T06:24:38Z",
      "headlineEligible": true,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T06:24:38Z",
      "witnessDigest": "records/2026-07-10/digest-29073710752-1.json"
    },
    "310ba3ac3dced599b8b6f5ce4905d2b28c5b9c5e29d4d58f764f8263c473d000": {
      "coverage": "direct",
      "custodyInventoryVersion": 1,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": false,
      "inventoryStatus": "legacy-incomplete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    },
    "32d5159168b82b6c8cc28732d2d392f6f4ab600a7bd1883084eedf1ec525269c": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T14:26:26Z",
      "headlineEligible": false,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T14:26:26Z",
      "witnessDigest": "records/2026-07-10/digest-29099746745-1.json"
    },
    "367af00e465db44e5d9261aba364c96da08a89e5e1cc21c47b20614e503c1d6a": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T06:24:38Z",
      "headlineEligible": true,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T06:24:38Z",
      "witnessDigest": "records/2026-07-10/digest-29073710752-1.json"
    },
    "37abd42372d1c9518e4f9b760221911b1709b11d6397053ad4be722408a4c690": {
      "coverage": "direct",
      "custodyInventoryVersion": 1,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": false,
      "inventoryStatus": "legacy-incomplete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    },
    "42ae848c76b1fc806c7deb25e7382017871880c697c946c6c0e205e8edd23fea": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T06:24:38Z",
      "headlineEligible": true,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T06:24:38Z",
      "witnessDigest": "records/2026-07-10/digest-29073710752-1.json"
    },
    "4430956d20921a9985502d0bbe6194550da0ed1362963ac7865133de3214ae76": {
      "coverage": "direct",
      "custodyInventoryVersion": 1,
      "earliestWitnessedAt": "2026-07-10T04:29:34Z",
      "headlineEligible": false,
      "inventoryStatus": "legacy-incomplete",
      "tsaGenTime": "2026-07-10T04:29:34Z",
      "witnessDigest": "records/2026-07-10/digest-genesis-enumeration-v1.json"
    },
    "4841e796ba4b926dbcf3a7c81829a45e5a262ae23318f0b077b4dbfcf42e1d32": {
      "coverage": "direct",
      "custodyInventoryVersion": 1,
      "earliestWitnessedAt": "2026-07-10T04:29:34Z",
      "headlineEligible": false,
      "inventoryStatus": "legacy-incomplete",
      "tsaGenTime": "2026-07-10T04:29:34Z",
      "witnessDigest": "records/2026-07-10/digest-genesis-enumeration-v1.json"
    },
    "4a84c6a6ec9003bcd6beda795838e9b589ac8cc4777e5792064c02bc3588dcd4": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T06:24:38Z",
      "headlineEligible": false,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T06:24:38Z",
      "witnessDigest": "records/2026-07-10/digest-29073710752-1.json"
    },
    "50406887feadfe8714eac6bf7eb58047a005427740429df80efb1ca36f0c1be4": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T14:05:53Z",
      "headlineEligible": true,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T14:05:53Z",
      "witnessDigest": "records/2026-07-10/digest-29098454379-1.json"
    },
    "541ba1752d0159c8f8080d2ec42f08596294230a2b202d59045178cee845acbf": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": true,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    },
    "57e1f9a22308e93feb98ab52132fdacdc89585b4b4df9fcfd98d5555bdb8c28e": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T06:24:38Z",
      "headlineEligible": true,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T06:24:38Z",
      "witnessDigest": "records/2026-07-10/digest-29073710752-1.json"
    },
    "5aa5460c31e318d31de15db41841c6cbf4409d097559edd77b9ea94f972687c0": {
      "coverage": "direct",
      "custodyInventoryVersion": 1,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": false,
      "inventoryStatus": "legacy-incomplete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    },
    "5ad4bb5b1606c7b25a5fa5b4f8c63ba173719ad4c08daef1758de128768a8bb7": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T15:29:57Z",
      "headlineEligible": false,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T15:29:57Z",
      "witnessDigest": "records/2026-07-10/digest-29103805372-1.json"
    },
    "5b9a337ac3cdbccf38f7e2055bc2479db455a2b8ffe24e403a584bb6f0d18f42": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": true,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    },
    "63d49e281db5cdf4c18c8e87120a5f2e1e5ffa24131e9e2496a346923601457c": {
      "coverage": "direct",
      "custodyInventoryVersion": 1,
      "earliestWitnessedAt": "2026-07-10T04:29:34Z",
      "headlineEligible": false,
      "inventoryStatus": "legacy-incomplete",
      "tsaGenTime": "2026-07-10T04:29:34Z",
      "witnessDigest": "records/2026-07-10/digest-genesis-enumeration-v1.json"
    },
    "640ef0c009d20dd4d829cb79c46350cc04ab6f389249b11dbdfc38802c8cf67a": {
      "coverage": "direct",
      "custodyInventoryVersion": 1,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": false,
      "inventoryStatus": "legacy-incomplete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    },
    "6672c59aea85186ef8e36c6aa8c5b4ad5961deb24ac21a1873ad6b87ed929521": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T15:29:57Z",
      "headlineEligible": false,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T15:29:57Z",
      "witnessDigest": "records/2026-07-10/digest-29103805372-1.json"
    },
    "69b267231a9218a5ed50a245ed70c5b223ac7080167c86ab5c466b1e4e2580c9": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": true,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    },
    "6c6efd94516cf8916fe9cc5ad452e2a6fb3fbd877e7b600949cdf4db92d77423": {
      "coverage": "direct",
      "custodyInventoryVersion": 1,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": false,
      "inventoryStatus": "legacy-incomplete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    },
    "70810516145f29d3904498be8e457f4486c2c1868f80d9b02c71bc2c2fb4ecc1": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T12:49:24Z",
      "headlineEligible": false,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T12:49:24Z",
      "witnessDigest": "records/2026-07-10/digest-29093775439-1.json"
    },
    "74277e5de71a872db96a98a2296c12f4efa679e83067075ace8ae190f948c049": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": false,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    },
    "7869d65029740fa938fb8cea9e7f8fdd2f7aaee0109044b702ea3c3b2ea44fbe": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T12:49:24Z",
      "headlineEligible": true,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T12:49:24Z",
      "witnessDigest": "records/2026-07-10/digest-29093775439-1.json"
    },
    "790fb493cccf107b6236eea1613e304d652c88764e9791658d452da7765c0fd5": {
      "coverage": "direct",
      "custodyInventoryVersion": 1,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": false,
      "inventoryStatus": "legacy-incomplete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    },
    "7a277db0f1d7c2cac5006f82a49c2e4fd7fefac70636339514f41c4091ac6f55": {
      "coverage": "direct",
      "custodyInventoryVersion": 1,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": false,
      "inventoryStatus": "legacy-incomplete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    },
    "7aa78973cb11f5841167fe5f19c97d35fd05137c88eb7e9a0103134fddc6f61d": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": true,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    },
    "7d29b22ef7e9aa08c38d4aea66b0495a1f46626b971f9f0dcaef5ce82d4d4743": {
      "coverage": "direct",
      "custodyInventoryVersion": 1,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": false,
      "inventoryStatus": "legacy-incomplete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    },
    "7e7cc9250e9b72c356aed3fc11c2507a142b5bdf4acd0df5bf32ac7ef6f73a82": {
      "coverage": "direct",
      "custodyInventoryVersion": 1,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": false,
      "inventoryStatus": "legacy-incomplete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    },
    "85a1618aa6d696d5832e8a7e1e1fa33cf8e4cf911d431938f8f05c01511fe2d5": {
      "coverage": "direct",
      "custodyInventoryVersion": 1,
      "earliestWitnessedAt": "2026-07-10T04:29:34Z",
      "headlineEligible": false,
      "inventoryStatus": "legacy-incomplete",
      "tsaGenTime": "2026-07-10T04:29:34Z",
      "witnessDigest": "records/2026-07-10/digest-genesis-enumeration-v1.json"
    },
    "865a023dce4beda122de512ce9c19e86d3a54a41237f19849ceaf7ac6e7d9a0e": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": true,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    },
    "86f996a99b36c4e202b0e1ac7fdb8b0f514e3d4f0d028bd2c3777099c9f3ddbd": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T15:29:57Z",
      "headlineEligible": false,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T15:29:57Z",
      "witnessDigest": "records/2026-07-10/digest-29103805372-1.json"
    },
    "88459e649496f8b1dad32afa626b804a175b0197b2a00eb50b976aed515e7e9d": {
      "coverage": "direct",
      "custodyInventoryVersion": 1,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": false,
      "inventoryStatus": "legacy-incomplete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    },
    "887b13578768fed6dbaa055c0480613b77fcbd4f2cb5999d6a302d60e15de31a": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T15:29:57Z",
      "headlineEligible": false,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T15:29:57Z",
      "witnessDigest": "records/2026-07-10/digest-29103805372-1.json"
    },
    "89b47fe5454290ca4bec40c1092b0347d128dbb007c1aa1774c99d4e8f01cd83": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T15:29:57Z",
      "headlineEligible": true,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T15:29:57Z",
      "witnessDigest": "records/2026-07-10/digest-29103805372-1.json"
    },
    "8d73a4821415bbe2c4242c9a1f1333d3bda808ee67be8a2672c5f4077e8073e3": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T12:49:24Z",
      "headlineEligible": false,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T12:49:24Z",
      "witnessDigest": "records/2026-07-10/digest-29093775439-1.json"
    },
    "8dfc94904806476a4e52f37bbb04ce6c714ac848566b68da2192abd90ec709fd": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T12:49:24Z",
      "headlineEligible": false,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T12:49:24Z",
      "witnessDigest": "records/2026-07-10/digest-29093775439-1.json"
    },
    "8e3c342503e583c9ed6d53bc6940b52c4770b659d8f529bfcf63ac2886bfe1c3": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T15:29:57Z",
      "headlineEligible": false,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T15:29:57Z",
      "witnessDigest": "records/2026-07-10/digest-29103805372-1.json"
    },
    "8fbcc19e71b4a007f1fe81413dad8d4bff5bfa0fa081412903cfc26c65914672": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T15:29:57Z",
      "headlineEligible": false,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T15:29:57Z",
      "witnessDigest": "records/2026-07-10/digest-29103805372-1.json"
    },
    "92286e85af4858382910a1013abcc7a2e6a59829f3795680c9b11007ddb17f45": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T15:29:57Z",
      "headlineEligible": false,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T15:29:57Z",
      "witnessDigest": "records/2026-07-10/digest-29103805372-1.json"
    },
    "95c87232a4b3c8e77a6c87068b6a38f6af4b98a599dd7a54ea3988c043e42f3f": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T15:29:57Z",
      "headlineEligible": false,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T15:29:57Z",
      "witnessDigest": "records/2026-07-10/digest-29103805372-1.json"
    },
    "96dc4cab8ba78a41dfe1499474c5a947511a9f9f80cd7e5173bd355bce94e013": {
      "coverage": "direct",
      "custodyInventoryVersion": 1,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": false,
      "inventoryStatus": "legacy-incomplete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    },
    "9a91ffc1861e06fb670ac6e92f1e5daa065d71047f0b1e1cc3bdbafcc8609c78": {
      "coverage": "direct",
      "custodyInventoryVersion": 1,
      "earliestWitnessedAt": "2026-07-10T04:29:34Z",
      "headlineEligible": false,
      "inventoryStatus": "legacy-incomplete",
      "tsaGenTime": "2026-07-10T04:29:34Z",
      "witnessDigest": "records/2026-07-10/digest-genesis-enumeration-v1.json"
    },
    "9ab34dad6c19ef04c1a1a5096b2d0e27d349f48f86bd61e3370cff736d2fa879": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T15:29:57Z",
      "headlineEligible": false,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T15:29:57Z",
      "witnessDigest": "records/2026-07-10/digest-29103805372-1.json"
    },
    "9c40b62677993805c0ea54526eacb6529d04d35f6b7fc9afc10523da4c911a16": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T06:24:38Z",
      "headlineEligible": false,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T06:24:38Z",
      "witnessDigest": "records/2026-07-10/digest-29073710752-1.json"
    },
    "9d9a6ad6ae7ed45a9b7b04d57e47c0e5a88284056e8856afcdd6ea210bc2b48a": {
      "coverage": "direct",
      "custodyInventoryVersion": 1,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": false,
      "inventoryStatus": "legacy-incomplete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    },
    "9e39409aa022202ad31e4302bb896c0368b461341bf7923fb05f4aee87dc58b6": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T15:29:57Z",
      "headlineEligible": false,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T15:29:57Z",
      "witnessDigest": "records/2026-07-10/digest-29103805372-1.json"
    },
    "a00114e2281e483add89f5a3288ffc3e1ce884ce9bce45acc358ff9e9f39f20d": {
      "coverage": "direct",
      "custodyInventoryVersion": 1,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": false,
      "inventoryStatus": "legacy-incomplete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    },
    "a4f73859c8127590ffeb579e513172102eedc592a3216d94e6ad0fcbe55ef1ef": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T14:05:53Z",
      "headlineEligible": true,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T14:05:53Z",
      "witnessDigest": "records/2026-07-10/digest-29098454379-1.json"
    },
    "a6482ae144fda9188c0a520dc98ba11cc2d8e6cc36cb8e58f3e375a8f356cfda": {
      "coverage": "direct",
      "custodyInventoryVersion": 1,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": false,
      "inventoryStatus": "legacy-incomplete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    },
    "a8d6413309e0030e6d6c50e4a74e1bc16a866a31f3808afea230d01f5a921bbb": {
      "coverage": "direct",
      "custodyInventoryVersion": 1,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": false,
      "inventoryStatus": "legacy-incomplete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    },
    "a9d83db73e30ec72b852f0d37ce3da615caf3495ef2be162cff46e1ac0e0423a": {
      "coverage": "direct",
      "custodyInventoryVersion": 1,
      "earliestWitnessedAt": "2026-07-10T04:29:34Z",
      "headlineEligible": false,
      "inventoryStatus": "legacy-incomplete",
      "tsaGenTime": "2026-07-10T04:29:34Z",
      "witnessDigest": "records/2026-07-10/digest-genesis-enumeration-v1.json"
    },
    "aa69125eb8bc772469215926bbefc735583ab515f03af761be2e29533c25714b": {
      "coverage": "direct",
      "custodyInventoryVersion": 1,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": false,
      "inventoryStatus": "legacy-incomplete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    },
    "afc8143dab19938ef2b7d480d98acaa5ac7d4e89dc87af0848dd738b9253b51f": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T15:29:57Z",
      "headlineEligible": false,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T15:29:57Z",
      "witnessDigest": "records/2026-07-10/digest-29103805372-1.json"
    },
    "b18425740a976a5e918d16fe5a1278eb7d609a38978eb9042ebe85d14c3dd3c3": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T15:29:57Z",
      "headlineEligible": false,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T15:29:57Z",
      "witnessDigest": "records/2026-07-10/digest-29103805372-1.json"
    },
    "b4b06965ffb44c3be32b8c3e8252b8c68bcb1bf3fe5e021cd4ad838c6c200f93": {
      "coverage": "direct",
      "custodyInventoryVersion": 1,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": false,
      "inventoryStatus": "legacy-incomplete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    },
    "c1f1a31b1294c53af52618b60bfbbf0b88ad6cdcd93a499cac620bafd7cf37ce": {
      "coverage": "direct",
      "custodyInventoryVersion": 1,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": false,
      "inventoryStatus": "legacy-incomplete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    },
    "c21b1e1c575eee5aadbb7c11d2eed56cda9773f457374b40deb1e4191300835f": {
      "coverage": "direct",
      "custodyInventoryVersion": 1,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": false,
      "inventoryStatus": "legacy-incomplete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    },
    "c2402e956b71d916f12fd7c5e029fc751c8e963cc9af6bf01e2fa28df8ab6a19": {
      "coverage": "direct",
      "custodyInventoryVersion": 1,
      "earliestWitnessedAt": "2026-07-10T04:29:34Z",
      "headlineEligible": false,
      "inventoryStatus": "legacy-incomplete",
      "tsaGenTime": "2026-07-10T04:29:34Z",
      "witnessDigest": "records/2026-07-10/digest-genesis-enumeration-v1.json"
    },
    "c501d6ec424f6ad6b801abf695347f3489fd87956601852d702958f465b29bcd": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": true,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    },
    "c9938940849ea52d64dddbb01339ba487696b0797fd2d9378ec2131f7891e532": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T14:05:53Z",
      "headlineEligible": true,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T14:05:53Z",
      "witnessDigest": "records/2026-07-10/digest-29098454379-1.json"
    },
    "cc040feecc31d6f8e127e4454c19e9ecb6d6646eb6016791bfc1ab90b7abc256": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T15:29:57Z",
      "headlineEligible": true,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T15:29:57Z",
      "witnessDigest": "records/2026-07-10/digest-29103805372-1.json"
    },
    "cd2ba811e6dc2cc9387592683c2da2f47139a556d5657a66689467bbffaf0929": {
      "coverage": "direct",
      "custodyInventoryVersion": 1,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": false,
      "inventoryStatus": "legacy-incomplete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    },
    "d2b519583435be5978281a687b51ac6384b1ff729d913816bd41340cd8090b87": {
      "coverage": "direct",
      "custodyInventoryVersion": 1,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": false,
      "inventoryStatus": "legacy-incomplete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    },
    "d32d0c9be100fefa2d5fe7be6d4eff5d4afa4b4d531c16ca3933b1ae562ed344": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": true,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    },
    "db27773957027b5e2c7affd4fb6479588d95b27ee0fb28ddc426e70e8f83b247": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T15:29:57Z",
      "headlineEligible": true,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T15:29:57Z",
      "witnessDigest": "records/2026-07-10/digest-29103805372-1.json"
    },
    "e2af66fed4fe21cb03fe23ecb0658f9c0faf1004768bdc47e9ccbd3fcb1134a7": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T14:26:26Z",
      "headlineEligible": true,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T14:26:26Z",
      "witnessDigest": "records/2026-07-10/digest-29099746745-1.json"
    },
    "e2f831e8def507c1e7a76cdf2211e6964147c75024b24e12f1cab25d46883875": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": true,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    },
    "e4055c28cfa45621eee8656badc445bb66f9be3833040e765b212b653021cd61": {
      "coverage": "direct",
      "custodyInventoryVersion": 1,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": false,
      "inventoryStatus": "legacy-incomplete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    },
    "e802e48ff45ba2fe59e4b303a994b400e51dffbdf46fea0ba18855b883b37841": {
      "coverage": "direct",
      "custodyInventoryVersion": 1,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": false,
      "inventoryStatus": "legacy-incomplete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    },
    "eb70ecd374f96ab5421416cbe86ded4d3a8ddfffab39520e6f5acf90da1f465d": {
      "coverage": "direct",
      "custodyInventoryVersion": 1,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": false,
      "inventoryStatus": "legacy-incomplete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    },
    "edf2bb0b5191faab3c9e263b0b9573909b358cdaaf1709d98fab9d6db3c76290": {
      "coverage": "direct",
      "custodyInventoryVersion": 1,
      "earliestWitnessedAt": "2026-07-10T04:29:34Z",
      "headlineEligible": false,
      "inventoryStatus": "legacy-incomplete",
      "tsaGenTime": "2026-07-10T04:29:34Z",
      "witnessDigest": "records/2026-07-10/digest-genesis-enumeration-v1.json"
    },
    "f559ef129a70c1e99360b75745caf0621e289767dd7a4505b3fa1e21113c3bbb": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T15:29:57Z",
      "headlineEligible": false,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T15:29:57Z",
      "witnessDigest": "records/2026-07-10/digest-29103805372-1.json"
    },
    "f86040f34e82fd1b85ec056ebed46306ada8df5d712f435a6613840db35b5126": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T15:29:57Z",
      "headlineEligible": false,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T15:29:57Z",
      "witnessDigest": "records/2026-07-10/digest-29103805372-1.json"
    },
    "f9ad2785bdb8494e02c76bd1b901a46100d9995635ba0f028f701c4bbf8d26e0": {
      "coverage": "direct",
      "custodyInventoryVersion": 1,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": false,
      "inventoryStatus": "legacy-incomplete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    },
    "fbeddd1e8c7765df73f4dbaedb9e842c7d1db1db90105f3a9127b0504e76f022": {
      "coverage": "direct",
      "custodyInventoryVersion": 1,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": false,
      "inventoryStatus": "legacy-incomplete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    },
    "fcc88609f40b1a3919dc42cb4976f2dbbd9b0362960e2dfe1e3474c507a87f35": {
      "coverage": "direct",
      "custodyInventoryVersion": 2,
      "earliestWitnessedAt": "2026-07-10T06:06:00Z",
      "headlineEligible": true,
      "inventoryStatus": "complete",
      "tsaGenTime": "2026-07-10T06:06:00Z",
      "witnessDigest": "records/2026-07-10/digest-29072912548-1.json"
    }
  };
