#!/usr/bin/env python3
"""Publish strategy-lane runs as comparison-run augments.

Three lanes land here, all attached to EXISTING catalog cells so they are
graded against the same resolutions as the headline runs:

- ladder: reviewed runs elicited as a threshold ladder of binary
  exceedance probabilities (promptMode ladder); their published CDF is
  built from the ladder rungs, not from a normal-around-the-interval.
- rollouts: plain fast runs, three per target, relabeled so readers can
  tell the samples apart.
- median3: derived median-of-rollouts runs from
  scripts/median_rollout_ensemble.py, published with the exact median CDF.

Everything is emitted into site/src/data/thesis-strategy-comparisons.ts as
STRATEGY_COMPARISON_RUN_AUGMENTS, merged onto cells alongside the existing
recorded-run augments.

Usage:
    python3 scripts/strategy_comparisons.py \
        --ladder-batch records/thesis-analyst/batches/....json \
        --rollout-batch records/thesis-analyst/batches/r1.json \
        --rollout-batch records/thesis-analyst/batches/r2.json \
        --rollout-batch records/thesis-analyst/batches/r3.json \
        --median-list /tmp/median-manifests.txt \
        [--out site/src/data/thesis-strategy-comparisons.ts]
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys
from typing import Any

ROOT = pathlib.Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "scripts"
DEFAULT_OUT = ROOT / "site" / "src" / "data" / "thesis-strategy-comparisons.ts"

sys.path.insert(0, str(SCRIPTS))
from thesis_records_to_comparisons import (  # noqa: E402
    comparison_run,
    effective_scale,
    repo_path,
    scaled,
)


def write_strategy_ts(out_path: pathlib.Path, augments: dict) -> None:
    body = json.dumps(augments, indent=2, ensure_ascii=True)
    run_ats = sorted(
        run["predictionRun"]["runAt"]
        for runs in augments.values()
        for run in runs
    )
    wave_line = (
        f"// Wave: {run_ats[0][:10]} ({sum(len(r) for r in augments.values())} "
        f"runs across {len(augments)} cells, "
        f"{run_ats[0]} - {run_ats[-1]}).\n"
        if run_ats
        else ""
    )
    out_path.write_text(
        "// Generated by scripts/strategy_comparisons.py from recorded\n"
        "// strategy-lane manifests (ladder / rollouts / median3).\n"
        f"{wave_line}"
        "// Regenerate; do not hand-edit.\n"
        'import type { ForecastComparisonRun } from "./forecast-cells";\n\n'
        "export const STRATEGY_COMPARISON_RUN_AUGMENTS: Record<\n"
        "  string,\n"
        "  ForecastComparisonRun[]\n"
        f"> = {body};\n"
    )

POINT_COUNT = 201


def batch_results(batch_paths: list[pathlib.Path]):
    for batch_path in batch_paths:
        batch = json.loads(repo_path(batch_path).read_text())
        for result in batch.get("results", []):
            if not result.get("ok"):
                continue
            target = result.get("target") or {}
            if not target.get("catalogSlug"):
                continue
            manifest = json.loads(repo_path(result["manifestPath"]).read_text())
            cells = json.loads(repo_path(result["cellsPath"]).read_text())
            if cells:
                yield target, manifest, cells[0]


def cdf_points_from_knots(
    knots: list[tuple[float, float]]
) -> list[dict[str, float]]:
    lower = knots[0][0]
    upper = knots[-1][0]
    step = (upper - lower) / (POINT_COUNT - 1)

    def cdf_at(value: float) -> float:
        if value <= knots[0][0]:
            return knots[0][1]
        for index in range(1, len(knots)):
            prev_value, prev_prob = knots[index - 1]
            knot_value, knot_prob = knots[index]
            if value <= knot_value:
                width = knot_value - prev_value
                if width <= 0:
                    return knot_prob
                return prev_prob + (value - prev_value) / width * (
                    knot_prob - prev_prob
                )
        return knots[-1][1]

    points = []
    for index in range(POINT_COUNT):
        value = upper if index == POINT_COUNT - 1 else lower + step * index
        points.append(
            {
                "value": round(value, 10),
                "probability": round(cdf_at(value), 10),
            }
        )
    return points


def ladder_distribution(
    cell: dict[str, Any], scale: float
) -> dict[str, Any] | None:
    ladder = cell.get("thresholdLadder")
    if not isinstance(ladder, dict):
        return None
    try:
        thresholds = [
            scaled(float(value), scale) for value in ladder["thresholds"]
        ]
        probs = [float(value) for value in ladder["cumulativeProbabilities"]]
    except (KeyError, TypeError, ValueError):
        return None
    if len(thresholds) != len(probs) or len(thresholds) < 3:
        return None

    point = scaled(cell["pointEstimate"], scale)
    ci_low = scaled(cell["ciLow"], scale)
    ci_high = scaled(cell["ciHigh"], scale)
    lower_spread = max(abs(float(point) - float(ci_low)), 1e-9)
    upper_spread = max(abs(float(ci_high) - float(point)), 1e-9)
    support_lower = min(float(ci_low) - lower_spread * 1.5, thresholds[0])
    support_upper = max(float(ci_high) + upper_spread * 1.5, thresholds[-1])

    knots: list[tuple[float, float]] = [(support_lower, 0.0)]
    previous_prob = 0.0
    for threshold, prob in zip(thresholds, probs):
        prob = min(max(prob, previous_prob), 1.0)
        if threshold <= knots[-1][0]:
            continue
        knots.append((threshold, prob))
        previous_prob = prob
    if support_upper > knots[-1][0]:
        knots.append((support_upper, 1.0))
    else:
        knots[-1] = (knots[-1][0], 1.0)

    points = cdf_points_from_knots(knots)
    return {
        "format": "numeric_cdf_v1",
        "pointCount": POINT_COUNT,
        "support": {
            "lower": points[0]["value"],
            "upper": points[-1]["value"],
        },
        "points": points,
        "summary": {
            "pointEstimate": point,
            "median": point,
            "interval80": {"lower": ci_low, "upper": ci_high},
        },
        "provenance": "agent_reported",
    }


def ladder_augments(
    batch_paths: list[pathlib.Path],
) -> dict[str, list[dict[str, Any]]]:
    augments: dict[str, list[dict[str, Any]]] = {}
    for target, manifest, cell in batch_results(batch_paths):
        slug = target["catalogSlug"]
        scale = effective_scale(
            cell, target.get("valueScale", 1), target.get("targetUnit")
        )
        run = comparison_run(
            cell, manifest, slug, target.get("valueScale", 1),
            target.get("targetUnit"),
        )
        run["label"] = "Threshold-ladder elicitation"
        run["predictionRun"]["runLabel"] = "Threshold-ladder elicitation"
        run["description"] = (
            "Reviewed thesis.analyst run elicited as a ladder of binary "
            "exceedance probabilities (P(first print <= t) across 11-15 "
            "rungs); the point and interval are interpolated from the "
            "ladder and the published CDF is the ladder itself. Protocol "
            "adapted from Turtel et al. 2025 (arXiv:2505.17989). "
            + run["description"]
        )
        distribution = ladder_distribution(cell, scale)
        if distribution:
            run["predictionDistribution"] = distribution
        augments.setdefault(slug, []).append(run)
    return augments


def rollout_augments(
    batch_paths: list[pathlib.Path],
) -> dict[str, list[dict[str, Any]]]:
    augments: dict[str, list[dict[str, Any]]] = {}
    for target, manifest, cell in batch_results(batch_paths):
        slug = target["catalogSlug"]
        run = comparison_run(
            cell, manifest, slug, target.get("valueScale", 1),
            target.get("targetUnit"),
        )
        augments.setdefault(slug, []).append(run)
    for slug, runs in augments.items():
        runs.sort(key=lambda run: run["predictionRun"]["runAt"])
        for index, run in enumerate(runs, start=1):
            label = f"Fast rollout {index} of {len(runs)}"
            run["label"] = label
            run["predictionRun"]["runLabel"] = label
            run["description"] = (
                "Independent fast rollout recorded for median prediction "
                "sampling (Turtel et al. 2025, arXiv:2505.17989). "
                + run["description"]
            )
    return augments


def median_augments(
    manifest_paths: list[pathlib.Path],
) -> dict[str, list[dict[str, Any]]]:
    augments: dict[str, list[dict[str, Any]]] = {}
    for manifest_path in manifest_paths:
        manifest = json.loads(repo_path(manifest_path).read_text())
        if not manifest.get("ok"):
            continue
        target = manifest.get("targetContext") or {}
        slug = target.get("catalogSlug")
        cells = json.loads(repo_path(manifest["cellsPath"]).read_text())
        if not slug or not cells:
            continue
        cell = cells[0]
        scale = effective_scale(
            cell, target.get("valueScale", 1), target.get("targetUnit")
        )
        run = comparison_run(
            cell, manifest, slug, target.get("valueScale", 1),
            target.get("targetUnit"),
        )
        label = "Median of 3 rollouts"
        run["label"] = label
        run["predictionRun"]["runLabel"] = label
        run["predictionRun"]["runDescription"] = (
            "Derived run: pointwise median of the constituent rollout CDFs "
            "(median prediction sampling, Turtel et al. 2025, "
            "arXiv:2505.17989). Deterministic aggregate of recorded "
            "rollouts; constituent manifests are in the activity log."
        )
        run["description"] = (
            "Pointwise median of three independent fast rollouts' CDFs — "
            "no new model call; the derived-distribution artifact and "
            "constituent manifests are recorded alongside the run."
        )
        distribution_path = None
        for artifact in manifest.get("artifacts", []):
            if artifact.get("artifactType") == "derived_distribution":
                distribution_path = artifact["path"]
        if distribution_path:
            distribution = json.loads(repo_path(distribution_path).read_text())
            if scale != 1:
                distribution["points"] = [
                    {
                        "value": scaled(point["value"], scale),
                        "probability": point["probability"],
                    }
                    for point in distribution["points"]
                ]
                distribution["support"] = {
                    "lower": scaled(distribution["support"]["lower"], scale),
                    "upper": scaled(distribution["support"]["upper"], scale),
                }
                summary = distribution["summary"]
                distribution["summary"] = {
                    "pointEstimate": scaled(summary["pointEstimate"], scale),
                    "median": scaled(summary["median"], scale),
                    "interval80": {
                        "lower": scaled(summary["interval80"]["lower"], scale),
                        "upper": scaled(summary["interval80"]["upper"], scale),
                    },
                }
            run["predictionDistribution"] = distribution
        augments.setdefault(slug, []).append(run)
    return augments


def merge(
    *sources: dict[str, list[dict[str, Any]]]
) -> dict[str, list[dict[str, Any]]]:
    merged: dict[str, list[dict[str, Any]]] = {}
    for source in sources:
        for slug, runs in source.items():
            merged.setdefault(slug, []).extend(runs)
    for runs in merged.values():
        runs.sort(key=lambda run: run["predictionRun"]["runAt"])
    return dict(sorted(merged.items()))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--ladder-batch", action="append", default=[], type=pathlib.Path
    )
    parser.add_argument(
        "--rollout-batch", action="append", default=[], type=pathlib.Path
    )
    parser.add_argument(
        "--median-manifest", action="append", default=[], type=pathlib.Path
    )
    parser.add_argument("--median-list", type=pathlib.Path)
    parser.add_argument("--out", type=pathlib.Path, default=DEFAULT_OUT)
    args = parser.parse_args()

    median_paths = list(args.median_manifest)
    if args.median_list and args.median_list.exists():
        median_paths.extend(
            pathlib.Path(line)
            for line in args.median_list.read_text().splitlines()
            if line.strip()
        )

    augments = merge(
        ladder_augments(args.ladder_batch),
        rollout_augments(args.rollout_batch),
        median_augments(median_paths),
    )
    write_strategy_ts(args.out, augments)
    total = sum(len(runs) for runs in augments.values())
    print(f"wrote {total} strategy runs across {len(augments)} cells -> {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
