#!/usr/bin/env python3
"""Regenerate the newest post-cutover wave and require byte-for-byte parity."""

from __future__ import annotations

import difflib
import json
import pathlib
import re
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parents[1]
EXAMPLES = ROOT / "site" / "src" / "data" / "forecast-examples"
# Earlier generated modules do not retain complete input-batch provenance and
# are deliberately grandfathered. Every generated dated module at/after this
# marker must carry a `Batch manifests` header and is reproducibility-gated.
WAVE_REPRODUCIBILITY_MARKER_DATE = "2026-07-10"


def dated_generated_modules() -> list[tuple[str, pathlib.Path]]:
    modules = []
    for path in EXAMPLES.glob("*.ts"):
        match = re.search(r"(20\d{2}-\d{2}-\d{2})", path.name)
        if not match or match.group(1) < WAVE_REPRODUCIBILITY_MARKER_DATE:
            continue
        if not path.read_text().startswith(
            "// Generated by scripts/spawned_cells_to_ts.py from recorded\n"
        ):
            continue
        modules.append((match.group(1), path))
    return sorted(modules, key=lambda item: (item[0], item[1].name))


def batch_inputs(batch_paths: list[pathlib.Path]) -> list[str]:
    winners: dict[str, str] = {}
    for batch_path in batch_paths:
        batch = json.loads(batch_path.read_text())
        for result in batch["results"]:
            slug = result["target"]["catalogSlug"]
            if result["ok"] and result.get("cellsPath"):
                winners[slug] = result["cellsPath"]
    if not winners:
        raise ValueError("recorded batch manifests contain no publishable cells")
    return sorted(set(winners.values()))


def main() -> int:
    modules = dated_generated_modules()
    if not modules:
        print(
            "wave reproducibility: no generated wave at/after marker "
            f"{WAVE_REPRODUCIBILITY_MARKER_DATE}; historical waves are grandfathered"
        )
        return 0

    _, module = modules[-1]
    committed = module.read_text()
    provenance_match = re.search(r"^// Batch manifests: (\[.*\])$", committed, re.M)
    if not provenance_match:
        print(
            f"wave reproducibility: {module.relative_to(ROOT)} lacks batch provenance",
            file=sys.stderr,
        )
        return 1
    batch_names = json.loads(provenance_match.group(1))
    batch_paths = [ROOT / name for name in batch_names]
    missing = [
        str(path.relative_to(ROOT)) for path in batch_paths if not path.is_file()
    ]
    if missing:
        print(
            f"wave reproducibility: missing batch manifest(s): {missing}",
            file=sys.stderr,
        )
        return 1
    const_match = re.search(
        r"^export const ([A-Z0-9_]+): ForecastCell\[\] =", committed, re.M
    )
    if not const_match:
        print(
            f"wave reproducibility: cannot find export constant in {module}",
            file=sys.stderr,
        )
        return 1

    inputs = batch_inputs(batch_paths)
    with tempfile.TemporaryDirectory() as temporary:
        regenerated = pathlib.Path(temporary) / module.name
        command = [
            sys.executable,
            str(ROOT / "scripts" / "spawned_cells_to_ts.py"),
            str(regenerated),
            const_match.group(1),
            *inputs,
            *sum((["--batch-manifest", str(path)] for path in batch_paths), start=[]),
            "--replace-module",
            str(module),
        ]
        completed = subprocess.run(
            command, cwd=ROOT, capture_output=True, text=True, check=False
        )
        if completed.returncode != 0:
            print(completed.stdout, file=sys.stderr)
            print(completed.stderr, file=sys.stderr)
            return completed.returncode
        actual = regenerated.read_text()

    if actual != committed:
        diff = "".join(
            difflib.unified_diff(
                committed.splitlines(keepends=True),
                actual.splitlines(keepends=True),
                fromfile=str(module.relative_to(ROOT)),
                tofile="regenerated",
            )
        )
        print(f"wave reproducibility drift:\n{diff}", file=sys.stderr)
        return 1
    print(f"wave reproducibility OK: {module.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
